### ISSUE TITLE
Example of how to actually serve the application using node?

### ISSUE THREAD

**Issue by mrweiner** [frandiox/vite-ssr#115]
I've ran the build and the dist/server directories are populated, but I don't really understand what I'm supposed to do to actually serve the application. I'm deploying to platform.sh, who has an example for node that includes:

```
# The configuration of app when it is exposed to the web.
web:
  commands:
    start: "node index.js"
```

So, in my app, I've replaced this with:
```
# The configuration of app when it is exposed to the web.
web:
  commands:
    start: "node dist/server/main.js"
```

That serves up a 502 error, though, so it would seem that things aren't running as expected. Similarly, if I run `node dist/server/main.js` locally, I don't seem to get any feedback that anything is happening. I'm essentially using https://github.com/frandiox/vitesse-ssr-template/blob/master/src/main.ts with minor additions.

I've never used node before so forgive my ignorance if I'm glancing over something obvious.
